INSERT INTO users(id, screen_name, password) VALUES(1, 'CNET', 'TENC');
INSERT INTO users(id, screen_name, password) VALUES(2, 'engadget', 'tegdagne');
INSERT INTO users(id, screen_name, password) VALUES(3, 'gadgetlab', 'baltegdag');
INSERT INTO users(id, screen_name, password) VALUES(4, 'Gizmodo', 'odomziG');
INSERT INTO users(id, screen_name, password) VALUES(5, 'mashable', 'elbahsam');
INSERT INTO users(id, screen_name, password) VALUES(6, 'TechCrunch', 'hcnurChceT');
INSERT INTO users(id, screen_name, password) VALUES(7, 'slashdot', 'todhsals');
INSERT INTO users(id, screen_name, password) VALUES(8, 'readwriteweb', 'bewetirwdaer');
INSERT INTO users(id, screen_name, password) VALUES(9, 'arstechnica', 'acinhcetsra');
INSERT INTO users(id, screen_name, password) VALUES(10, 'WiredFeed', 'deeFderiW');

INSERT INTO tweets(user_id, text, retweet_count) VALUES(1, 'AT&amp;T''s LG Optimus G will be available November 2 for $199.99 http://t.co/V6UZC68F', 2);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(1, 'RT @b1g1nj4p4n: Windows 8 delivers the goods on benchmarks (mostly) says CNET Labs: http://t.co/Uzy9Rj3S', 8);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(1, 'The Linksys EA6500 has the potential to be a great router, but for now it''d be a bad deal at half the price (review) http://t.co/9AVut4ha', 4);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(1, 'Hands-on with nifty iCade 8-Bitty: Cool controller, yeah, but it doesn''t have enough games http://t.co/3diWzjXK', 2);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(1, '3 awesome smartphone word games you may not know about http://t.co/34xBaW6p', 13);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(1, 'If you don''t pick up this Survival Kit, don''t come looking to borrow ours when the Zombies come http://t.co/fMdLiIFu', 26);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(1, 'Just what is Windows RT, anyway? (FAQ) http://t.co/5np6vojt', 13);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(1, 'How to add emoticons to your Facebook chats and messages http://t.co/WEREXAKY', 14);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(1, 'Turns out people really are interested in moving as much of their digital stuff as they can into the cloud http://t.co/PJjC4g2D', 15);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(1, 'Have you heard the news? Seriously, have you? Catch @CNETUpdate for all the tech goodness you may have missed: http://t.co/FqybLwdo', 3);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(1, 'How to manage your iTunes subscriptions http://t.co/OLinwjzr', 11);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(1, 'Facebook photos of undercover cop get woman arrested http://t.co/pMSGqHJN', 16);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(1, 'RT @CNETNews: Smart skivvies shock patients to prevent bedsores http://t.co/pq775JrR #electricunderwear', 11);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(1, 'Watch the 24-mile skydive from Felix Baumgartner''s point of view http://t.co/6BLq6ePv', 45);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(1, 'Brace yourself: Microsoft Surface ad deluge may start tonight http://t.co/TgPJVSAU', 16);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(1, '65 years ago, Capt. Charles E. Yeager made history by becoming the first pilot to fly faster than the speed of sound http://t.co/nbLoqOAH', 22);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(1, 'Watch the 24-mile skydive from Felix Baumgartner''s point of view! http://t.co/6BLq6ePv', 47);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(1, 'Siri''s got a brand new boss: Apple has reportedly tapped an ex-Amazon exec to oversee the voice-assistant http://t.co/PyBawtuS', 19);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(1, 'RT @CNETNews: Softbank has a 300-year plan to save Sprint customers from loneliness and despair http://t.co/SnNcoI9F', 10);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(1, 'We tear down the PS3 Super Slim and what do we find? Some hardware changes, but no real upgrades http://t.co/wGdQflQn', 16);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(2, 'Yahoo hires Google exec Henrique de Castro as COO -  http://t.co/wJjvvTMH', 7);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(2, 'LG Optimus G brings 13-megapixels of shooting prowess to Sprint on November 11th for $200 -  http://t.co/jW7yX9Ut', 14);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(2, 'Google tests searches that include Calendar, Drive in results -  http://t.co/wwsYesTk', 20);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(2, 'Must See HDTV (October 15th - 21st) -  http://t.co/yngTk5hP', 5);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(2, 'CyberPower reveals Fang III Taipan SLI gaming notebook -  http://t.co/X1C1Bi0n', 7);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(2, 'Join the Engadget HD Podcast live on Ustream at 6:30PM ET -  http://t.co/gjr2yJkG', 4);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(2, 'Simple.TV finally starts shipping to backers, latecomers can still order for $149 and up -  http://t.co/ZI9pLKzd', 8);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(2, 'RT @EngadgetDistro: “Are some people simply better drivers of technology?” —@fruhlinger (Issue 61) http://t.co/RiHuxJ6G', 8);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(2, 'Apple snags Amazon''s A9 head to lead Siri team -  http://t.co/EwAtVIzs', 32);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(2, 'Tips have 13-inch MacBook Pro with Retina display joining iPad mini at rumored Apple event -  http://t.co/qggJFZjx', 28);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(2, '"The image—we''re not working with actors and dialogue—that''s what we were after." —Ron Fricke on @Samsarafilm (http://t.co/LUMaUF7f)', 3);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(2, 'Jolla''s Marc Dillon takes over as CEO, Jussi Hurmola to focus on Sailfish -  http://t.co/tMkCbVYZ', 6);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(2, 'Editorial: Betting on BlackBerry (or hoping) -  http://t.co/N2JhAWW0', 27);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(2, 'Galaxy Nexus, Nexus S start receiving Android 4.1.2 over the air -  http://t.co/ZJfp2gol', 51);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(2, 'Zeiss Cinemizer head-mounted OLED display wends its way into stores -  http://t.co/97QCyPf2', 11);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(2, 'AT&amp;T LG Optimus G to be available November 2 for $200 -  http://t.co/XF7i0TEU', 7);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(2, 'With the launch of Xbox Music, Zune is truly no more -  http://t.co/4STyYk3A', 34);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(2, '''Samsara'' creators Ron Fricke and Mark Magidson discuss the digital filmmaking divide (video) -  http://t.co/4ntYsDUQ', 11);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(2, 'Ooma HD2 handset and Linx adapter available on Oct.17 for $60 and $50, respectively -  http://t.co/MouBYqE1', 4);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(3, 'Simple.TV Starts Shipping Streaming DVR http://t.co/DbZqj0zw by @strngwys', 8);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(3, 'Raspberry Pi Gets A Double Slice of RAM http://t.co/YY6sJDhB by @strngwys', 13);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(3, 'How Google and Samsung Can Make a 10-Inch Nexus Tablet Rock http://t.co/jaG2jgph by @nateog', 22);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(3, 'On this week''s Gadget Lab Show, we talk Lytro and adventures in #walletless paradise: http://t.co/s0wFFDMn', 5);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(3, '12 Most Annoying Technologies as Chosen by Wired Commenters http://t.co/983PhrYo by @strngwys', 28);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(3, 'Does your iPad feel incomplete? Here are 8 pieces of flair to dress it up: http://t.co/FGCpDc1A', 29);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(3, 'Microsoft Estimated to Spend $1.5 Billion on Windows 8 Marketing: http://t.co/vWOwa95k by @alexandra_chang', 27);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(3, 'Swiss Federal Railways licenses iconic Swiss clock design used in iOS 6 to Apple http://t.co/NcHSBWb9', 14);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(3, 'Windows 8 software and devices pre-orders start today. Are you pre-ordering anything? http://t.co/yEghH97y by @alexandra_chang', 17);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(3, 'iPad Mini event now expected for Oct. 23, just two days before Microsoft Surface event http://t.co/3LqwGNCI by @redgirlsays', 36);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(3, 'RIM Leaks New BlackBerry Phone on Video http://t.co/LMZAFORF by @strngwys', 15);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(3, 'Roth Ceramic Subwoofer Drops That Bass http://t.co/oJJmptaU by @strngwys', 6);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(3, 'Apple patent expands on biometric identification implementations (and would look good, to boot) http://t.co/njSCk5KG by @redgirlsays', 15);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(3, 'Political Polling Evolving to Match Mobile Lifestyles http://t.co/127K9K1C by @mat', 2);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(3, 'DirecTV’s New DVR Records 5 Shows at Once, Streams to Multiple TVs http://t.co/bIYv3ks9 by @nateog', 10);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(3, 'Samsung Galaxy S III Mini: Big Compromise in a Smaller Package http://t.co/6w547kXQ by @nateog', 23);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(3, 'Teardown: iPod touch shows us its guts http://t.co/fiDvhBEs by @redgirlsays', 7);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(3, 'Capacitive Touch Case Makes Your iPhone Very Sensitive http://t.co/jNNRmtXq by @strngwys', 6);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(3, 'U.S. Appeals Court Lifts Galaxy Nexus Sales Ban http://t.co/fgJf2qHV by @redgirlsays', 8);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(3, '.@redgirlsays'' #walletless adventures continue... ''Going Walletless on Vacation: First Challenge, Airport Security'' http://t.co/F9qA1Ras', 5);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(4, 'First supersonic man Chuck Yeager breaks speed of sound again 65 after his first historic flight: http://t.co/7sr6QtVV', 40);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(4, 'Can you imagine San Francisco without any people or moving cars? Watch it: http://t.co/hAxFAQoS', 41);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(4, 'Retina MacBook Pro: The best worst laptop I''ve ever owned: http://t.co/CgFlBowV', 61);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(4, 'Nikon wants to make a throwing your camera to take a picture "feature" http://t.co/jDtvlTkq', 34);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(4, 'You can crash this RC helicopter as many times as you want http://t.co/OwCBqjez', 11);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(4, 'You can use emoticons on Facebook now. Our favorite is the (^^^) http://t.co/CPp9Lq9l', 49);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(4, 'Where does your college rank on the list of top 50 torrenting campuses? http://t.co/K75wvTv0', 25);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(4, 'Dear lame whiners, Instagram is awesome: http://t.co/NWm3uEhL', 54);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(4, 'No wonder Street View is so good when Google has this army of cars: http://t.co/IPYcp3od', 85);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(4, 'Amazon quietly discontinuing the Kindle DX: http://t.co/hOS7kqZh', 20);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(4, 'Softbank confirms 70 percent acquisition of Sprint: http://t.co/WMHCjWrf', 33);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(4, 'First head cam video of supersonic space jump. Terrifying and awesome! http://t.co/RTPDGZBU', 240);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(4, 'Is Apple planning to launch 13-Inch Retina MacBook Pro this month? http://t.co/NYJy8OQr', 41);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(4, 'This is what it''s like to photograph the wreckage of Fukushima: http://t.co/Tks9js8c', 40);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(4, 'It''s official: the space jump daredevil went supersonic! Watch the moment of the jump here: http://t.co/raXeylH2', 219);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(4, 'Felix Baumgartner made a crazy awesome space jump, but would you?  http://t.co/lBKx6hOp', 38);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(4, 'Could these be the actual iPad Mini prices? http://t.co/7kfbw5q8', 55);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(4, 'An animated GIF of the space jump was urgently needed. Here it is! http://t.co/39d3eguQ', 141);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(4, 'Watch the amazing video replay of the space jump here! This is crazy: http://t.co/ildAWA5L', 436);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(4, 'That record-shattering space jump? It''s finally happening right now: http://t.co/oOYjGucX', 86);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(5, '.@Twitter is Experiencing Outages http://t.co/LPXjBGZq', 10);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(5, 'Tiniest Alien Solar System Discovered http://t.co/i9LVmRT5', 41);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(5, 'Researchers Suggest Faster-Than-Light Travel Theoretically Possible http://t.co/stIBMGpw', 33);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(5, 'Play a 3D-Printed Acoustic Guitar Made of Plastic http://t.co/JWDEBxDp @psfk', 24);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(5, 'Don''t Be Fooled: These Are Not Real Muppets http://t.co/oWQb47hZ', 15);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(5, 'Low Income Students'' Test Scores Leap 30% With Smartphone Use http://t.co/JGYDHL7W', 99);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(5, 'Kit Kat Sent Chocolate Bar Into Space to Keep Felix Company [VIDEO]  http://t.co/qbuL30tb', 37);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(5, 'Yahoo Poaches Top Google Exec to be New COO http://t.co/UYVvzmb8', 47);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(5, 'Twitter Seeks Woman for Its All-Male Board [REPORT]   http://t.co/beDmfYcD', 79);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(5, 'Microsoft Surface Joins Twitter and Facebook http://t.co/x4rxFy6p', 41);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(5, 'Music Monday: What Song Would You Choose for a Space Jump?  http://t.co/CyzZnjbp', 19);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(5, '''Diary of a Wimpy Kid'' E-Book Series Goes on Pre-Order for Kindle  http://t.co/alnemWfc', 13);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(5, 'Feds pilot ‘rapid DNA’ to potentially identify casualties, immigrants http://t.co/My8uL5nr (via @Nextgov)', 12);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(5, 'Tap Dancing Zombies Star in Soulless Musical [VIDEO] http://t.co/Y6hHYUDS', 18);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(5, 'Yes, the Space Jump Mattered - http://t.co/RyTk90zP', 71);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(5, 'Apple Hires Amazon Exec to Take Control of Siri - http://t.co/rWJAthqH', 65);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(5, '10 New York Comic Con Pictures You Can''t Unsee - http://t.co/MkTVc5eW', 40);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(5, 'MLB Scoring a Home Run With Apple’s Passbook - http://t.co/kj4gObmW', 21);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(5, 'Etsy Accused of Exploiting Breast Cancer Awareness Month - http://t.co/sqE9CJgQ via @dailydot', 37);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(5, 'Stunning Time-Lapse Video Shows Beauty of our World - http://t.co/TOBBt6W2', 51);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(6, 'What Would Paul Graham Do? -- A Search Engine That Teaches You The Ways Of Y Combinator''s Boss http://t.co/GhFHK48L by @joshconstine', 9);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(6, 'ZocDoc CEO Cyrus Massoumi On Making Medicine More Tech-Savvy, One Appointment At A Time [TCTV] http://t.co/HRZY2W0m by @loyalelectron', 13);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(6, 'Google Opens The Doors A Bit Wider For Gmail Results Within Its Main Search Experience http://t.co/T2BUZHsM by @thatdrew', 25);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(6, 'Tweetie Creator Loren Brichter''s Next Act: Atebits 2.0 To "Make Fun And Useful Things" [Like Games] http://t.co/CAVXn9Wx by @romaindillet', 8);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(6, 'The Voice Gets A Mobile Karaoke App, Thanks To StarMaker http://t.co/7Ca88URv by @anthonyha', 19);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(6, 'Keen On... The Daily Dot: Does The Internet Really Need A Daily Newspaper About Itself? [TCTV] http://t.co/QaK6v323 by @ajkeen', 6);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(6, 'GoodBlogs Allows Companies To Effortlessly Maintain A Blog About Their Industry To Drive Traffic http://t.co/LUuT9LHu by @romaindillet', 25);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(6, 'Esri Acquires Location Platform Geoloqi, Plans To Launch Alternative iOS Mapping Library Soon  http://t.co/o91Rnvdu by @fredericl', 24);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(6, 'Luxury Smartphone Brand Vertu Keeps Current CEO, Names Nokia Alum Anssi Vanjoki Chairman  http://t.co/yaPOKy5C by @chrisvelazco', 17);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(6, 'Hipster Coffee Lovers Rejoice, Blue Bottle Coffee Raises $20M http://t.co/4BSboV17 by @thatdrew', 62);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(6, 'Fight Evil Mutant Corn With Facebook Promote And Prop 37: http://t.co/hNMinmQU via @Uncrunched', 16);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(6, 'Apple Taps Amazon Search Exec To Helm Siri, Signals A Move To A Smarter Personal Shopping Assistant http://t.co/3oOJBoFA by @drizzled', 28);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(6, 'Streak Raises $1.9 Million For Gmail-Based CRM App http://t.co/JZJ65XPJ by @alexwilliams', 20);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(6, 'Meet The New Foursquare, The One That You''ve Helped Build And Continue To Power http://t.co/S9iwbsFP by @thatdrew', 61);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(6, 'The Hidden Radio: A Bluetooth Speaker With Cloistered Virtue And Some Obvious Flaws http://t.co/tePVQeZm by @drizzled', 1);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(6, 'Dropbox''s "Great Space Race" Lets College Students Win Up To 25GB Of Free Storage Space For Two Years http://t.co/18v8orak by @fredericl', 43);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(6, '$199 LG Optimus G Will Hit AT&amp;T Shelves November 2, Pre-Orders Start October 16 http://t.co/QvhVZjaa by @jordanrcrook', 11);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(6, 'With Its Gamification Tools, SessionM Reports A 35 Percent Lift In Retention, 250 Percent Lift In Eng... http://t.co/WZjkjGts by @anthonyha', 19);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(6, 'Head Cam Footage From Felix Baumgartner''s Edge-Of-Space Skydive http://t.co/1YAgFtdz by @ferenstein', 71);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(7, 'Post-ACTA Agreement CETA Moving Forward With Similar Provisions http://t.co/jLyOHoM0', 6);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(7, 'Physicists Propose "Perpetual Motion" Time Crystals http://t.co/gpwGvv0a', 8);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(7, 'These 19th Century Postcards Predicted Our Future http://t.co/ZsxV4ich', 10);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(7, 'FBI Issues Android Virus Warning http://t.co/slwqiXS6', 22);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(7, '"Dance Your Ph.D." Winner Announced http://t.co/skiMrplt', 11);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(7, 'FCC To Allow Cable Companies To Encrypt Over-the-Air Channels http://t.co/hZYFAZaZ', 7);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(7, 'CIA: Flying Skyhook Wasn''t Just For James Bond, It Actually Rescued Agents http://t.co/aR4YWlwb', 7);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(7, 'Cancer-Detecting Bra Could One Day Surpass Mammograms In Accuracy http://t.co/pp76sKaY', 17);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(7, 'Is a Wireless Data Center Possible? http://t.co/7hdOg5Jh', 10);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(7, 'Is a wireless data center possible? (SlashDataCenter) http://t.co/w121b4nY', 4);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(7, 'Book Review: Everyday Cryptography http://t.co/3xvAo6Zz', 7);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(7, 'Pinterest analytics on the rise (SlashBI) http://t.co/RzeSZ9CI', 1);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(7, 'Symphony of Self-Destruction: strengthening security with a Red Team (SlashBI) http://t.co/TFqgwTyl', 2);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(7, 'The UAE Claims To Hold the Worlds Largest Biometric Database http://t.co/mByd3AMq', 5);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(7, 'McAfee launches data center security suites (SlashDataCenter) http://t.co/aBqr6Cns', 0);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(7, '$3,000 Tata Nano Car Coming To US http://t.co/BVlqsZMK', 12);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(7, 'Amateur Planet Hunters Find First Planet In a Four-Star System  http://t.co/WMHufpBz', 7);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(7, 'Bruce Perens To Answer Your Questions http://t.co/sX7gVFMF', 2);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(7, 'Precision Espionage MiniFlame Malware Tied To Flame http://t.co/lHv6QJwk', 5);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(7, 'KDE Plasma Active 3 Improves Performance, Brings New Apps http://t.co/HNAHkcKW', 4);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(8, 'THERE WILL BE NO FURTHER UPDATES ON THIS A/C. Please follow @rww for all future ReadWriteWeb updates. That is our official a/c now.', 6);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(8, 'Who''s Getting Hired in Tech? Q1 Numbers from ReadWriteHire http://bit.ly/14VLg', 2);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(8, 'More Failed Negotiations: YouTube Now Also Blocks Music Videos in Germany http://bit.ly/adxM0', 1);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(8, 'Evernote for iPhone 2.0: Now More Finger-Friendly http://bit.ly/1bXliD', 1);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(8, 'Mike Mackley: Motorola, Time Warner mixing up multiroom, tru2way cable setups due later this year (via FriendFeed) http://bit.ly/R99A', 0);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(8, 'Sideline: Yahoo Releases Desktop Client for Real-Time Twitter Search http://bit.ly/123ynM', 0);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(8, 'How Tough Is It Today Being a VC? 10 Questions for Two Early-Stage Stars http://bit.ly/rxL9', 1);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(8, 'Zoho Introduces Chat 2.0 http://bit.ly/UU0AP', 2);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(8, 'Nomee Introduces New Social Aggregation Software http://bit.ly/2taA', 0);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(8, 'Ebay Launches Selling Manager Applications Beta http://bit.ly/u7mcM', 1);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(8, 'Super Rewards Launches Virtual Currency Platform http://bit.ly/2ps4o', 0);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(8, 'Sprout Adds Social Platform Support http://bit.ly/4xOfiE', 0);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(8, 'Zehra Nasif: 25 highly anticipated open-source releases coming this year (via FriendFeed) http://bit.ly/r0btb', 1);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(8, 'Talis Takes on Amazon With Pot of Structured Data in the Sky http://bit.ly/89Kjw', 0);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(8, 'Lunch Launches a Personal Recommendation Network (+Invites) http://bit.ly/BaiGr', 0);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(8, 'Tinker Builds Microblog Communities Around Topics http://bit.ly/GO2cH', 1);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(8, 'Why You Have to Use the Standalone Google Contacts Page http://bit.ly/NywSC', 2);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(8, 'What''s Wrong with Facebook? When Strategy Fails to Meet Execution http://bit.ly/nIWn', 0);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(8, 'MySpace Goes Local: Announces Partnership with Citysearch http://bit.ly/ptWVH', 1);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(8, 'What Can Voice Do For You? Ribbit Announces Winners of KillerApps Challenge http://bit.ly/XNzWu', 0);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(9, 'Apple nabs Amazon search expert to take charge of Siri http://t.co/WFCHjcbV by @foresmac', 14);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(9, 'How a single DMCA notice took down 1.45 million education blogs http://t.co/SpHIP7lY by @JBrodkin', 53);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(9, 'Congressman warns FTC: Leave Google alone http://t.co/DgdnQX1r by @binarybits', 20);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(9, 'Future of computing has Schrödinger''s cat inside http://t.co/sVhbkD9F by @exMamaku', 33);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(9, '13" Retina MacBook Pro rumored to share iPad mini spotlight next week http://t.co/vx2ilLmp by @eJacqui', 25);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(9, 'Xbox Music officially announced for Windows 8, iOS, and Android http://t.co/s30mEI10 by @Ohthatflo', 20);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(9, 'Solar panel control systems vulnerable to hacks http://t.co/Tw8mlMvg by @dangoodin001', 7);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(9, 'The Dealmaster: A trackpad, a chair, and all things in between http://t.co/sSjQL3h3 by @Lee_Ars', 6);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(9, 'EA coupon glitch lets Origin users download dozens of free games http://t.co/VFYcWqhE by @KyleOrl', 12);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(9, 'Beached whale? Amazon pulls Kindle DX from store, death may be imminent http://t.co/cxTH6BQo by @caseyjohnston', 10);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(9, '10,000 UK protestors demand Google censor anti-Islam video http://t.co/reprDdbi by @binarybits', 18);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(9, 'Hard drive replacement program now covers iMacs sold from 2009-2011 http://t.co/WhFZGV81 by @eJacqui', 20);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(9, 'Sprint agrees to $20B merger, says extra cash will boost LTE rollout http://t.co/uzTq9Ijc by @JBrodkin', 24);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(9, 'Rayman developer: Wii U GamePad latency is 1/60th of a second http://t.co/cHPR7qfl by @KyleOrl', 15);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(9, 'RT @acdha: As you''d expect, @arstechnica is actually analyzing their comment rating system http://t.co/ziuWVwk5', 7);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(9, 'RT @Urraca: "How swords, track changes, and Amazon led to The Mongoliad: Book Two" includes a 40-minute exclusive video interview http:/ ...', 4);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(9, 'Raspberry Pi now comes with double RAM at the same price http://t.co/b1Y8bcqo by @thepacketrat', 35);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(9, 'Editorial: Meet a science committee that doesn''t get science http://t.co/W8lzG3xg by @j_timmer', 46);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(9, 'My car is smarter than me—and I get better gas mileage for it. http://t.co/fyBIhYoT by @drgitlin', 9);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(10, 'Simple.TV Starts Shipping Streaming DVR: The battle for your cord-cutting dollars is heating up. A gaggle of dev... http://t.co/xfaPtP4h', 1);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(10, 'Gallery: Cosplay Eye Candy From New York Comic Con: To make his alluring portraits, photographer Sen?n Llanos fo... http://t.co/tsLQeUhw', 0);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(10, 'Alleged CIA Mole Says He Played Matchmaker for Al-Qaida Propagandist: Morten Storm is either a serial liar or a ... http://t.co/eBdlxig2', 1);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(10, 'Steal This Campaign-Finance Tracking Widget: Ask any politician whether campaign contributions influence their d... http://t.co/HVRu7D9y', 0);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(10, 'Why is a Nashville Fashion Blog Big in Riyadh?: Facebook is a land of foreign visitors, phantom robots, and clic... http://t.co/E1SNSrPa', 0);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(10, 'Know-It-All App Lets You Learn Without Thinking: Do you struggle to remember the periodic table of elements, but... http://t.co/dAwT7jNa', 1);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(10, 'Paleontologists Reveal the Identity of ''Predator X'': In 2009, journalists heralded the arrival of ?Predator X? ?... http://t.co/T16SBVeD', 0);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(10, 'Bringing Babysitting Into the iPhone Era: For parents under the illusion they still have a social life, finding ... http://t.co/3tKmyw23', 0);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(10, 'Raspberry Pi Gets a Double Slice of RAM: The Raspberry Pi micro-computer can''t compete with the latest all-in-on... http://t.co/TCn5gZuQ', 1);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(10, 'The Following Will Make You Love Serial-Killer Cults: The gory TV show will bring a creepy new kind of murder ma... http://t.co/gp59ncTx', 0);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(10, 'Sprint''s $20 Billion Deal Could Mean Lower Rates for All: The takeover of Sprint by Japanese mobile phone compan... http://t.co/iVDuLUM5', 0);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(10, '''Fearless'' Felix''s Awesome Supersonic Jump — In Lego!: We love this YouTube video of Felix Baumgartner''s stratos... http://t.co/S52WTrN6', 1);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(10, 'Two Congressmen Think Military Railroaded Officer Who Taught ''Total War'' on Islam: Two members of Congress want ... http://t.co/umQhL11g', 0);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(10, 'SpaceX Engine Failure Claims Experimental Satellite: SpaceX and NASA are forming a board to jointly investigate ... http://t.co/v1bqkYvK', 1);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(10, 'Tatooine Times Two: Amateur Astronomers Find Planet in Four-Star System: A group of volunteers at a citizen scie... http://t.co/D7jdkPqD', 1);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(10, '12 Reasons Microsoft''s Spotify Competitor, Xbox Music, Might Not Be Doomed: Microsoft has failed with its past m... http://t.co/nmANrovq', 1);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(10, 'Pentagon Fears Syrian Rebel Weapons Pose Proliferation Risk: The Pentagon insists that it''s not arming the Syria... http://t.co/jd6UL3Jj', 1);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(10, 'Easily Preview Responsive Designs With ''Responsivator'': Showing off responsive designs to your clients can be tr... http://t.co/Ifa8QPRC', 0);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(10, 'Transgendered Bellbird Found in New Zealand: Biologists at the Zealandia eco-sanctuary in New Zealand have spott... http://t.co/DWQSM56f', 0);
INSERT INTO tweets(user_id, text, retweet_count) VALUES(10, 'Red Bull Stratos: Why Didn''t Felix Free Fall for 5 Minutes?: Well, he did it. Felix jumped out of a balloon 128,... http://t.co/PcAN7wVc', 3);
